<div class="field frame_name required">
        <label class="label" for="frame_name"><span><?php echo __('Option Name') ?></span></label>
        <div class="control">
    <select name="frame_name" id="frame_name" title="<?php echo __('Option Name') ?>" class="input-text" data-validate="{required:true}">
        <option value=""><?php echo __('Please Select Frame .') ?></option>
            <option value="value1"><?php echo __('Frontend Option 1') ?></option>    
        <option value="value2"><?php echo __('Frontend Option 2') ?></option>    
        <option value="value3"><?php echo __('Frontend Option 3') ?></option>    
        <option value="value4"><?php echo __('Frontend Option 4') ?></option>    
        <option value="value5"><?php echo __('Frontend Option 5') ?></option>    
        </select>
        </div>
           	</div>
           	<div class="field frame_color required">
                          	<label class="label" for="frame_color">
<span><?php echo __('Option Title') ?></span>
</label>
                          	<div class="control">
                          	<select name="frame_color" id="frame_color" title="<?php echo __('Option Title') ?>" class="input-text" data-validate="{required:true}">
                             	<option value=""><?php echo __('Please Select Option') ?></option>    
                          	</select>
                          	</div>
           	</div>
 
<script>
   jQuery(document).on('change','#frame_name',function() {
            	 var param = 'frame='+jQuery('#frame_name').val();
            	 jQuery.ajax({
                            	 showLoader: true,
                            	 url: '<?php echo $block->getframeAction(); ?>',
                            	 data: param,
                            	 type: "GET",
                            	 dataType: 'json'
            	 }).done(function (data) {
                            	 jQuery('#frame_color').empty();
                            	 jQuery('#frame_color').append(data.value);
            	 });
    });
</script>
